fs=2000;
[A1,f]=fantransc(Acceleration_1,fs);
[A2,f]=fantransc(Acceleration_2,fs);
[A3,f]=fantransc(Acceleration_3,fs);
[A4,f]=fantransc(Acceleration_4,fs);
[A5,f]=fantransc(Acceleration_5,fs);
[F1,f1]=fantransc(Force_1,fs);
[F2,f1]=fantransc(Force_2,fs);
[F3,f1]=fantransc(Force_3,fs);
[F4,f1]=fantransc(Force_4,fs);
[F5,f1]=fantransc(Force_5,fs);
H=((A1./F1)+(A2./F2)+(A3./F3)+(A4./F4)+(A5./F5))/5;
r=real(H);
subplot(2,1,1);
plot(f,r);
xlabel('Frequency(Hz)');
ylabel('Magnitude (m/N*s^2)');
title('real part of FRF');
axis([0 300 -10 10]);
imagI=imag(H);
subplot(2,1,2);
plot(f,imagI,'m');
xlabel('frequency (Hz)');
ylabel('magnitude (m/N*s^2)');
title('imaginary part of FRF');
axis([0 300 -10 10]);