clc;
clear all;
close all;
load ('trail1lab1.mat');
s1=10.2*10^(-3);
s2=2.3*10^(-3);
Acceleration_1=(data(:,2))/s1;
Force_1=data(:,1)/s2;
load('trail2lab1.mat');
Acceleration_2= data(:,2)/s1;
Force_2=data(:,1)/s2;
load ('trail3lab1.mat');
Acceleration_3= data(:,2)/s1;
Force_3=data(:,1)/s2;
load ('trail4lab1.mat');
Acceleration_4= data(:,2)/s1;
Force_4=data(:,1)/s2;
load('trail5lab1.mat') ;
Acceleration_5= data(:,2)/s1;
Force_5=data(:,1)/s2;
subplot(2,1,1);
plot(time,Acceleration_4);
xlabel('time(sec)');
ylabel ('Acceleration (m/s^2)');
title('Acceleration Plot for Measurement1');
subplot(2,1,2);
plot (time,Force_5);
xlabel ('time(sec)');
ylabel ('force(N)');
title('Force Plot for Measurement1');